### ISSUE TITLE
Transfer Backend over

### ISSUE THREAD

**Issue by Kha1r0** [MoViDe-Project/motis#1]
The backend needs to be transferred to the visual-debugger/backend folder as a subfolder so it can later be called by the frontend.

# Acceptance Criteria

- created subfolder with existing code base in branch branching from master, in coherence with dev/frontend-template

# Story Points

- 2 Points

# Completed in Iteration

- 

# Actual Time in hours

- 4 hours

**Comment by Kvnstrck** [comment]
closed due to restructure
