### ISSUE TITLE
Create Frontend

### ISSUE THREAD

**Issue by Kha1r0** [MoViDe-Project/motis#2]
User needs to access the landing page that shows some of the motis svelte components

### Acceptance Criteria

- a svelte component from the motis project is visible on the landing page

### Story Points

- 2 Points

### Proposed completion in Iteration

- 2

### Marked as completed in Iteration

- 2

### Actual Time in hours

**Comment by Kha1r0** [comment]
frontend template created

**Comment by Kha1r0** [comment]
waiting for #5

**Comment by MoPhliFra** [comment]
@D3vZro, Dominik und ich checken nicht wie wir die components aus der motis/ui app in unsere motis/visual-debugger app importieren können, ohne dass ein Fehler wegen $lib geworfen wird. Vielleicht kannst du mal probieren ob das bei dir auch ist.

**Comment by Kha1r0** [comment]
[switched to sveltekit ](https://github.com/MoViDe-Project/motis/commit/22504aad90a9e1678f9b0ceab050889bcb7aa832)
