### ISSUE TITLE
Make Frontend talk to Backend

### ISSUE THREAD

**Issue by Kha1r0** [MoViDe-Project/motis#3]
The User should be able to see test data processed by the backend.

### Acceptance Criteria

- frontend shows test data made available by the backend

### Story Points

- 5 Points

### Proposed completion in Iteration

- 2

### Marked as completed in Iteration

- 

### Actual Time in hours

**Comment by Kha1r0** [comment]
![IMG_2684](https://github.com/user-attachments/assets/a3d030d2-b1e9-4115-90d8-30143f35d39e)

**Comment by Kvnstrck** [comment]
closes with #10
